name: houbago
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25
  flutter_secure_storage: ^9.0.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  record: ^5.0.4
  permission_handler: ^11.0.1
  uuid: ^4.1.0
  just_audio: ^0.9.35
  cupertino_icons: ^1.0.2
  barcode_widget: ^2.0.4
  card_swiper: ^3.0.1
  font_awesome_flutter: ^10.6.0
  animations: ^2.0.11
  fl_chart: ^0.63.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  timeago: ^3.6.0
  sqflite: ^2.3.0
  http: ^1.1.0
  audio_session: ^0.1.18
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
