name: houbago
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  barcode_widget: ^2.0.4
  image_picker: ^1.0.4
  google_fonts: ^5.1.0
  card_swiper: ^3.0.1
  font_awesome_flutter: ^10.6.0
  animations: ^2.0.11
  fl_chart: ^0.63.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  timeago: ^3.6.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
